POST http://localhost:5000/recipe/add HTTP/1.1
content-type: application/json
token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTJkMWM3OTFkODBkYmQ5OTUzNzc4ODYiLCJpYXQiOjE2OTc0NTUyNjEsImV4cCI6MTY5NzU0MTY2MX0.UNwkhdHZ0SjYwh0qBnj4UrlBxlRJtziHhUVGonL4-VA

{
    "name": "lody torty",   
    "description": "test4",
    "ingredients": [    
        {
            "name": "maka",
            "amount": 1,
            "unit": "test"
        }
    ],
    "instructions": [  
        "st2ep1"
    ],
    "tags": ["lody", "torty"],
    "difficulty": "easy",
    "calories": 100,
    "portions": 1,
    "time": 130
    
}
    
