POST http://localhost:8080/recipe/add HTTP/1.1
content-type: application/json
token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGUzNTFlNThhYmUxYzU3Zjk3ZWZjYzEiLCJpYXQiOjE2OTI2MTkyNDUsImV4cCI6MTY5MjcwNTY0NX0.cuTKPgNSdgVszGRh3aviQkpxQBJKpP1bAudHYPGt19I

{
    "name": "testw2",
    "description": "test3",
    "ingredients": [
        {
            "name": "tes5t",
            "amount": 1,
            "unit": "test"
        },
         {
            "name": "składnik2",
            "amount": 5,
            "unit": "kg"
        }
    ],
    "instructions": [
        {
            "description": "test"
        }
    ],
    "instructions": [
        "st2ep1",
        "ste5p2",
        "step3"
    ],
    "type": "breakfast",
    "difficulty": "easy",
    "calories": 100,
    "portions": 1
    
}
    
