POST http://localhost:5000/recipe/add HTTP/1.1
content-type: application/json
token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTBiMDkzOWNmMWIzMDkwZWMxN2JkNmIiLCJpYXQiOjE2OTYwMDgwMzksImV4cCI6MTY5NjA5NDQzOX0.acslyPqsxoQ0QpuybdwKIuughCeNbSQuAx6NqWF_43M

{
    "name": "test ze zdjęciem",   
    "description": "test3",
    "ingredients": [    
        {
            "name": "maka",
            "amount": 1,
            "unit": "test"
        },
         {
            "name": "mleko",
            "amount": 5,
            "unit": "kg"
        },
        
         {
            "name": "piwo",
            "amount": 5,
            "unit": "kg"
        }
    ],
    "instructions": [  
        "st2ep1",
        "ste5p2",
        "step3"
    ],
    "tags": ["ciasta", "kebaby"],
    "difficulty": "easy",
    "calories": 100,
    "portions": 1
    
}
    
