POST http://localhost:5000/comment/recipe/650af30f372599d74e10c214 HTTP/1.1
content-type: application/json
token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTBiMDkzOWNmMWIzMDkwZWMxN2JkNmIiLCJpYXQiOjE2OTU5MjIwNTEsImV4cCI6MTY5NjAwODQ1MX0.icx6srGRjPdWf_eyVK5mHF7ZDn52Z6cTCkwWey5rNlM

{
    "comment": "3"
}