POST http://localhost:5000/image/user HTTP/1.1
content-type: image/jpeg
token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGUzNTFlNThhYmUxYzU3Zjk3ZWZjYzEiLCJpYXQiOjE2OTUxNDI5NTQsImV4cCI6MTY5NTIyOTM1NH0.vJeFl1YRXBtUU8P7Ibcv_gedLneizXnfgteuirQKA6w

< ./download.jpg