DELETE http://localhost:5000/user/delete HTTP/1.1
content-type: application/json
token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTBiMDkzOWNmMWIzMDkwZWMxN2JkNmIiLCJpYXQiOjE2OTY1MTU3NTEsImV4cCI6MTY5NjYwMjE1MX0.wcK9wmCwLjMO_B6cbFwhSecvHGxfjuzKHc3GiqY7v14

{
}
    
