GET http://localhost:5000/user HTTP/1.1
content-type: application/json
token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTBiMDNkMDIwMGZlOTY1YTIwMGNhNDAiLCJpYXQiOjE2OTUyMjE3NjIsImV4cCI6MTY5NTMwODE2Mn0.gl7oinDKf7xES8PO7ob68uDvxpIQvGbtBvD7Da0xLh0

{
}
    
