POST http://localhost:8080/user/myProfile HTTP/1.1
content-type: application/json
token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGI4MDY4OWNmZDljZmZiMGE2OGQ2NjgiLCJpYXQiOjE2ODk3ODY4OTgsImV4cCI6MTY4OTg3MzI5OH0.hibgFOWnvK1jpgyBSoeI_DaM-ih6TLwlPa9dujM7qnI

{

}
    
