POST http://localhost:5000/user/register HTTP/1.1
content-type: application/json

{
    "firstName": "John2",
    "lastName": "Johnson",
    "userName": "Johnsonws",
    "email": "test2@test.pl",
    "password": "awdawdasS1!"
}