POST http://localhost:5000/user/register HTTP/1.1
content-type: application/json

{
    "firstName": "John",
    "lastName": "Johnson",
    "userName": "Johnsonwss",
    "email": "test2@test2.pl",
    "password": "awdawdasS1!"
}